weights: ./weights/yolov5m6.pt
cfg: ./models/yolov5m6.yaml
data: data/CustomData.yaml
hyp: data/hyp.custom.yaml
epochs: 2500
batch_size: 32
img_size:
- 1280
- 1280
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: ./train_result
entity: null
name: '20210709'
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: train_result\202107093
total_batch_size: 32
